function plotUSV(cdata1, cdata2, cdata3, cmaps)
%CREATEFIGURE(cdata1, cdata2, cdata3)
%  CDATA1:  image cdata
%  CDATA2:  image cdata
%  CDATA3:  image cdata
 
%  Auto-generated by MATLAB on 27-Feb-2020 15:19:45
 
% Create figure
figure1 = figure('NumberTitle','off',...
'Name','U,S,V matrices',...
'Color',[1 1 1]);
set(gcf,'color','white');set(gcf,'position',[200 200 600 200]);

% Create axes
axes1 = axes('Parent',figure1,'Position',[0.1 0.25 0.225 0.65]);
hold(axes1,'on');
 
% Create image
image(cdata1,'Parent',axes1,'CDataMapping','scaled');

% Apply red/blue colormap
colormap(axes1,cmaps.rbmap);
 
% Create ylabel
ylabel('7047 proteomes');
 
% Create xlabel
xlabel('7047 left SVs');
 
% Create title
title('U');
 
% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[0.5 7047.5]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0.5 7047.5]);
box(axes1,'on');
axis(axes1,'ij');
% Set the remaining axes properties
set(axes1,'CLim',[-0.06 0.06],'Layer','top','XTick',[],'YTick',[]);
% Create colorbar
colorbar('peer',axes1,'Position',[0.2525 0.1 0.075 0.03],...
'Ticks',[-0.06 0 0.06],...
'TickLabels',{'-0.06','0','0.06'},'Orientation','Horizontal');
 
% Create axes
axes2 = axes('Parent',figure1,'Position',[0.41 0.25 0.2 0.65]);
hold(axes2,'on');
 
% Create image
image(cdata2,'Parent',axes2,'CDataMapping','scaled');

% Apply red colormap
colormap(axes2,cmaps.redmap);
 
% Create ylabel
ylabel('7047');
 
% Create xlabel
xlabel('7047');
 
% Create title
title('\Sigma');
 
% Uncomment the following line to preserve the X-limits of the axes
xlim(axes2,[0.5 6815.5]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes2,[0.5 8224.5]);
box(axes2,'on');
axis(axes2,'ij');
% Set the remaining axes properties
set(axes2,'CLim',[0 2000],'Layer','top','XTick',[],'YTick',[]);
% Create colorbar
colorbar('peer',axes2,'Position',[0.535 0.1 0.075 0.03],'Ticks',[0 2000],...
'TickLabels',{'0','2000'},'Orientation','Horizontal');
 
% Create axes
axes3 = axes('Parent',figure1,'Position',[0.7 0.25 0.2 0.65]);
hold(axes3,'on');
 
% Create image
image(cdata3,'Parent',axes3,'CDataMapping','scaled');
 
% Apply red/blue colormap
colormap(axes3,cmaps.rbmap);

% Create ylabel
ylabel('10177 OGGs');
 
% Create xlabel
xlabel('7047 right SVs');
 
% Create title
title('V');
 
% Uncomment the following line to preserve the X-limits of the axes
xlim(axes3,[0.5 7047.5]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes3,[0.5 10177.5]);
box(axes3,'on');
axis(axes3,'ij');
% Set the remaining axes properties
set(axes3,'CLim',[-0.06 0.06],'Layer','top','XTick',[],'YTick',[]);
% Create colorbar
colorbar('peer',axes3,'Position',[0.825 0.1 0.075 0.03],...
'Ticks',[-0.06 0 0.06],...
'TickLabels',{'-0.06','0','0.06'},'Orientation','Horizontal');
 
