function plotDOGGZOGG(cdata1, cdata2, cmaps)
%CREATEFIGURE(cdata1, cdata2)
%  CDATA1:  image cdata
%  CDATA2:  image cdata

%  Auto-generated by MATLAB on 27-Feb-2020 14:28:27

% Create figure
figure1 = figure('NumberTitle','off','Name','Dij and Xij matrices',...
    'Color',[1 1 1]);

% Modify figure dimensions/position
set(gcf,'position',[200 200 700 200]);

% Create axes
axes1 = axes('Parent',figure1,'Position',[0.1 0.1 0.3 0.8]);
hold(axes1,'on');

% Create image
image(cdata1,'Parent',axes1,'CDataMapping','scaled');

% Apply redmap
colormap(axes1,cmaps.redmap);

% Create ylabel
ylabel('7047 proteomes');

% Create xlabel
xlabel('10177 OGGs');

% Create title
title('DOGG');

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[0.5 10177.5]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0.5 7047.5]);
box(axes1,'on');
axis(axes1,'ij');
% Set the remaining axes properties
set(axes1,'CLim',[0 5],'Layer','top','XTick',[],'YTick',[]);
% Create colorbar
colorbar('peer',axes1,'Position',[0.41 0.1 0.025 0.3],'Ticks',[0 5],...
    'TickLabels',{'0','5+'});

% Create axes
axes2 = axes('Parent',figure1,'Position',[0.6 0.1 0.3 0.8]);
hold(axes2,'on');

% Create image
image(cdata2,'Parent',axes2,'CDataMapping','scaled');

% Apply red/blue map
colormap(axes2,cmaps.rbmap);

% Create ylabel
ylabel('7047 proteomes');

% Create xlabel
xlabel('10177 OGGs');

% Create title
title('ZOGG');

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes2,[0.5 10177.5]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes2,[0.5 7047.5]);
box(axes2,'on');
axis(axes2,'ij');
% Set the remaining axes properties
set(axes2,'CLim',[-1 1],'Layer','top','XTick',[],'YTick',[]);
% Create colorbar
colorbar('peer',axes2,'Position',[0.91 0.1 0.025 0.3],'Ticks',[-1 0 1],...
    'TickLabels',{'-1','0','1'});

